# Generated by Django 6.0.1 on 2026-01-25 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título do Cenário')),
                ('description', models.TextField(verbose_name='Contexto (O que o aluno deve analisar?)')),
                ('difficulty', models.CharField(choices=[('easy', 'Iniciante'), ('medium', 'Intermediário'), ('hard', 'Avançado')], default='easy', max_length=10)),
                ('chart_data', models.JSONField(verbose_name='Dados do Gráfico (OHLC JSON)')),
                ('correct_action', models.CharField(choices=[('BUY', 'Comprar (Long)'), ('SELL', 'Vender (Short)'), ('WAIT', 'Aguardar')], max_length=4)),
                ('explanation', models.TextField(verbose_name='Explicação Técnica (Por que essa é a resposta?)')),
                ('cost_to_play', models.PositiveIntegerField(default=10, verbose_name='Custo em Moedas')),
                ('reward_xp', models.PositiveIntegerField(default=20, verbose_name='Recompensa de XP')),
            ],
        ),
        migrations.CreateModel(
            name='UserScenarioAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_action', models.CharField(max_length=4)),
                ('is_correct', models.BooleanField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.tradescenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
